### PR TITLE
Fix build on Darwin

### LINKED ISSUE #20: Compile failure on Darwin
As seen in [this issue for NixOs](https://github.com/NixOS/nixpkgs/pull/153860) compillation fails for Mac. The partial log reveals the issue to be with the systemstat crate:

```
  |
59 |                 .meminfo
   |                  ^^^^^^^ unknown field
   |
   = note: available fields are: `active`, `inactive`, `wired`, `cache`, `free`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `rust-motd` due to 2 previous errors
builder for '/nix/store/bjacpn3wsxavnp362dp86vnk8z7v69bm-rust-motd-0.2.0.drv' failed with exit code 101
error: build of '/nix/store/bjacpn3wsxavnp362dp86vnk8z7v69bm-rust-motd-0.2.0.drv' failed
```

Apparently it implements different fields for different OS's using conditional compilation ([e.g.](https://github.com/unrelentingtech/systemstat/blob/ad3a0a2c1e0577dd28b9a653d352f31a34528123/src/data.rs#L40)). 

A solution would be to add conditional compilation of our own to reference the available fields when compiling for Mac, and test that the compilation succeeds when cross compiling for the x86_64 and aarch64 darwin targets.

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
Fixes #20 

- Conditionally ignore memory stats on non linux/android platforms. Darwin is not supported by systemstat (https://github.com/unrelentingtech/systemstat/issues/73).
- Fixed a error output string for MemoryError

Thanks @amfl

### CODE REVIEW

File: src/components/memory.rs [hunk 1]
```diff
@@ -10,6 +10,10 @@ pub enum MemoryError {
     #[error("Could not find memory quantity {quantity:?}")]
     MemoryNotFound { quantity: String },
 
+    #[allow(dead_code)]
+    #[error("Getting memory information is not supported on the current platform")]
```
Comment (MarcelRobitaille) [inline src/components/memory.rs:14]: Should we link to the relevant issue (https://github.com/rust-motd/rust-motd/issues/20) here?

File: src/main.rs [hunk 2]
```diff
@@ -103,7 +103,7 @@ async fn main() -> Result<(), Box<dyn std::error::Error>> {
 
             if let Some(memory) = config.memory {
                 disp_memory(memory, &config.global, &sys, bar_size_hint) // TODO:
-                    .unwrap_or_else(|err| println!("Filesystem error: {}", err));
+                    .unwrap_or_else(|err| println!("Memory error: {}", err));
```
Comment (MarcelRobitaille) [inline src/main.rs:106]: Nice catch :)

**Review by MarcelRobitaille — CHANGES_REQUESTED** [review]
I have no way to test this, but it seems like a reasonable workaround.

File: src/components/memory.rs (hunk 1 above)
Comment (NickLarsenNZ) [reply src/components/memory.rs:14]: As a code comment, or in the error text?

**Comment by NickLarsenNZ** [comment]
I ran it on my Mac, the warnings are still there but if you like I can allow `dead_code` and `unused_variables`?

**Comment by NickLarsenNZ** [comment]
Oh, also I'm working on Mac support for systemstat so hopefully will have something soon.

File: src/components/memory.rs (hunk 1 above)
Comment (MarcelRobitaille) [reply src/components/memory.rs:14]: I was thinking in the error message so that users can see why it's unsupported.

**Comment by MarcelRobitaille** [comment]
> Oh, also I'm working on Mac support for systemstat so hopefully will have something soon.

I hope so as well. We could also consider switching to heim as recommended in that issue.

File: src/components/memory.rs (hunk 1 above)
Comment (NickLarsenNZ) [reply src/components/memory.rs:14]: Oh right. I'm not sure it's all that helpful for an end user and just ends up being noise. It is useful for a developer, thought they can find it through references in the commit messages.

I can add it if it's a show stopper though.

Comment (MarcelRobitaille) [reply src/components/memory.rs:14]: I think it's important to let people know why something is not working. I guess in this case it isn't very helpful if the solution is that it's not supported on their computer. I just really hate those error messages that are super vague and difficult to debug, so maybe I'm projecting from that.

I think the users of this program are very technical. Maybe it will matter so much to someone that they follow this discussion and make a PR switching to heim.

I guess it's not a show stopper for me. I would also be fine with a short "(see issue #20)" (no link).

Comment (NickLarsenNZ) [reply src/components/memory.rs]: Sounds fair. I've pushed the change now.
